export const conditions = [
  { weathercode: 0, condition: 'Clear sky' },
  { weathercode: 1, condition: 'Mostly clear' },
  { weathercode: 2, condition: 'Partly cloudy' },
  { weathercode: 3, condition: 'Overcast' },
  { weathercode: 45, condition: 'Fog' },
  { weathercode: 48, condition: 'Depositing rime and fog' },
  { weathercode: 51, condition: 'Light drizzle' },
  { weathercode: 53, condition: 'Moderate drizzle' },
  { weathercode: 55, condition: 'Dense drizzle' },
  { weathercode: 56, condition: 'Light freezing Drizzle' },
  { weathercode: 57, condition: 'Dense freezing Drizzle' },
  { weathercode: 61, condition: 'Slight rain' },
  { weathercode: 63, condition: 'Moderate rain' },
  { weathercode: 65, condition: 'Heavy rain' },
  { weathercode: 66, condition: 'Light freezing Rain' },
  { weathercode: 67, condition: 'Heavy freezing Rain' },
  { weathercode: 71, condition: 'Slight snowfall' },
  { weathercode: 73, condition: 'Moderate snowfall' },
  { weathercode: 75, condition: 'Slight snowfall' },
  { weathercode: 77, condition: 'Snow grains' },
  { weathercode: 80, condition: 'Slight rain shower' },
  { weathercode: 81, condition: 'Moderate rain shower' },
  { weathercode: 82, condition: 'Heavy rain showers' },
  { weathercode: 85, condition: 'Slight snow showers' },
  { weathercode: 86, condition: 'Heavy snow showers' },
  { weathercode: 95, condition: 'Thunderstorm with hail' },
  { weathercode: 96, condition: 'Thunderstorm with hail' },
  { weathercode: 99, condition: 'Thunderstorm with heavy hail' },
];
